- name: Gather the package facts
  package_facts:
    manager: auto
  tags:
  - CCE-83386-3
  - accounts_password_pam_unix_rounds_system_auth
  - configure_strategy
  - low_complexity
  - medium_disruption
  - medium_severity
  - no_reboot_needed
  when:
  - accounts_password_pam_unix_rounds_system_auth | bool
  - configure_strategy | bool
  - low_complexity | bool
  - medium_disruption | bool
  - medium_severity | bool
  - no_reboot_needed | bool
